#pragma once

#define CACHE_LINE_SIZE 128

#define SINGLE_OPERAND_ARITHMETIC 0
#define CONDITIONAL 1
#define TWO_OPERAND_ARITHMETIC 2
#define EMULATED 3

#define WORD_OPERATION 0
#define BYTE_OPERATION 1
