#pragma once

#define CACHE_LINE_SIZE 128

#define SINGLE_OPERAND_ARITHMETIC 0
#define CONDITIONAL 1
#define TWO_OPERAND_ARITHMETIC 2
#define EMULATED 3

#define WORD_OPERATION 0
#define BYTE_OPERATION 1

#define REGISTER_PC 0
#define REGISTER_SP 1
#define REGISTER_SR 2
#define REGISTER_CONST 3


